# Generated by Django 5.1.2 on 2025-07-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_product_category_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullorder',
            name='phone_no',
            field=models.CharField(null=True),
        ),
    ]
