# Generated by Django 5.1.2 on 2025-07-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_fullorder_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
    ]
