# Generated by Django 5.1.2 on 2024-11-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_supplier_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='users',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
